name: uGamemodeGUI
version: '${project.version}'
main: de.urbance.main.Main
author: Martin / Urbance
api-version: 1.18
commands:
  gmgui:
    description: GUI Management
  gm:
    description: Open Gamemode GUI
permissions:
  gmgui.*:
    description: Permissions for access to all commands
  gmgui.gamemode.*:
    description: Permission to change gamemode to survival, creative, spectator, adventure via GUI
  gmgui.gamemode.survival:
    description: Permission to change gamemode to survival via GUI
  gmgui.gamemode.creative:
    description: Permission to change gamemode to creative via GUI
  gmgui.gamemode.spectator:
    description: Permission to change gamemode to spectator via GUI
  gmgui.gamemode.adventure:
    description: Permission to change gamemode to adventure via GUI
  gmgui.open:
    description: Permission for open the GUI
  gmgui.reload:
    description: Permission the reload the config
  gmgui.version:
    description: Shows the current plugin version
  gmgui.editGUI:
    description: Allows you to edit the GUi.
  gmgui.help:
    description: Show help