name: uGamemodeGUI
version: '${project.version}'
main: de.urbance.main.Main
author: Martin / Urbance
api-version: 1.18
commands:
  gmgui:
    description: GUI Management
  gm:
    description: Open Gamemode GUI
permissions:
  gmgui.*:
    description: Access to all commands
  gmgui.gm.*:
    description: Open the GUI / Change to all available gamemodes
  gmgui.gm.survival:
    description: Permission to change gamemode to survival via GUI
  gmgui.gm.creative:
    description: Permission to change gamemode to creative via GUI
  gmgui.gm.spectator:
    description: Permission to change gamemode to spectator via GUI
  gmgui.gm.adventure:
    description: Permission to change gamemode to adventure via GUI
  gmgui.gm.open:
    description: Permission for open the GUI
  gmgui.modify:
    description: Allows you to edit the GUi.